### ISSUE TITLE
Mistyping prompt filename adds empty directory with mistyped prompt name to mirascope/versions

### ISSUE THREAD

**Issue by wcbudz** [Mirascope/mirascope#71] opened 2024-02-09 15:40 UTC
In the cli, if a prompt name is mistyped, e.g. `mirascope add bookrecommendation` when the prompt filename is bookrecommendations.py, the console returns the error "No such file or directory:  '/directory/location/bookrecommendation.py'"
The mistyped prompt name is then still added as an empty directory within /versions

If the file doesn't exist, preferred behavior would be to return the same error but not write the empty directory to /versions.

Ideal behavior would be:
`% mirascope add bookrecommendation`
`FileNotFoundError: [Errno 2] No such file or directory: '/Directory/location/bookrecommendation.py'`
`Did you mean bookrecommendations.py [Y/n]?`

And then create the directory and version if Y and not if n.

**Comment by wcbudz** [comment] 2024-02-09 16:15
This might be resolved by swapping the order of when the prompt versions directory is defined (currently line 96 `prompt_versions_directory = os.path.join(version_directory_path, prompt_file_name`) and the check for if the prompt file exists (currently lines 98 -102 `# Check if prompt file exists
if not os.path.exists(f"{prompt_directory_path}/{prompt_file_name}.py"):
    raise FileNotFoundError(
        f"Prompt {prompt_file_name}.py not found in {prompt_directory_path}"
    )` )

**Comment by willbakst** [comment] 2024-02-09 23:08
Duplicate of #37

**Closed** 2024-02-09 23:09 UTC
Labels: bug, prompt cli
