### ISSUE TITLE
Invalid tool call argument

### ISSUE THREAD

**Issue by off6atomic** [Mirascope/mirascope#359] opened 2024-07-25 11:36 UTC
### Description

I ran the following code:

```py
from typing import Literal
from pydantic import BaseModel

from mirascope.openai import OpenAICall, OpenAICallParams

class WeatherInput(BaseModel):
    location: Literal["Bangkok", "Tokyo"]

def get_current_weather(
    weather_input: WeatherInput
):
    """Get the current weather in a given location."""
    print(weather_input)

class Forecast(OpenAICall):
    prompt_template = "What's the weather in California?"

    call_params = OpenAICallParams(
        model="gpt-4", tools=[get_current_weather], tool_choice="required"
    )


tool = Forecast().call().tool
if tool:
    print("Tool arguments:", tool.args)
    tool.fn(**tool.args)
```

and got this error:
```
ValidationError: 1 validation error for get_current_weather
weather_input.location
  Input should be 'Bangkok' or 'Tokyo' [type=literal_error, input_value='California', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/literal_error
```

I'm expecting the LLM to choose arbitrary location from the literal list but instead it chose invalid value that is not in the list.
Is this kind of expected? If yes, I'm just trying to understand how to handle arguments that do not fit the schema like this.
I saw that the error happens very often. In some cases, if I I specify the argument type as `str | None`, the LLM decided to put in 0 as argument instead. Doesn't happen all the time but it's often enough to be frustrating.

### Python, Mirascope & OS Versions, related packages (not required)

```
mirascope=0.18.2
```

**Comment by willbakst** [comment] 2024-07-30 01:40
I've found that this is common when using Enum/Literal for tool calls unfortunately.

There are two things I generally use to combat this:
1. Additional prompt engineering (ranging from field descriptions to examples)
2. Reinsertion of validation errors back into the prompt and trying again (retries).

The upcoming v1 release will have better convenience around this collection/reinsertion of the errors.

**Comment by off6atomic** [comment] 2024-07-30 10:09
OK. So it seems very important to wrap the tool call with try-except block then otherwise your app could produce uncaught exceptions all the time.

I'll wait to see how error handling is done in v1.
Maybe we can close this issue once we have a good example code for showing how to do error handling?

**Comment by willbakst** [comment] 2024-07-30 16:10
Yeah, you'll likely want to wrap calls such as `response.tools` or `response.tool` in a try/except to catch any validation errors. Even in v1 with retries, you'll likely want to stop after some number of retries and gracefully handle the error. With tenacity, you can still add things such as exponential decay, but at a certain point it's likely better to expect there's an issue that needs to be resolved beyond reinserting the error (for example, if it still fails after 5 times, it likely won't succeed on the 6th).

We will make sure that our documentation is very clear around how we recommend to best handle `ValidationError` cases.

**Comment by off6atomic** [comment] 2024-07-31 13:13
Right now in v0.18.0, I'm not sure how to handle the validation error properly.

This is my code:
```py
tool_stream = OpenAIAsyncStream(generator)
        session_id = str(uuid.uuid4())
        async for chunk, tool in tool_stream:
            if tool:
                tool_call = tool.tool_call

                # yield the tool call with extra fields
                yield {
                    "role": "tool_call",
                    "session_id": session_id,
                    **tool_call.model_dump(),
                }

                with logfire.span(
                    f"Tool: {tool_call.function.name}", tool_call=tool_call
                ) as span:
                    start_time = time.perf_counter()
                    output = tool.fn(**tool.args)
                    execution_time = time.perf_counter() - start_time
                    span.set_attributes(
                        {"output": output, "execution_time": execution_time}
                    )
                    logfire.info(
                        "Execution time: {execution_time:.3f} seconds",
                        execution_time=execution_time,
                    )
                tool_output = create_tool_message(tool_call, output)
                yield tool_output
```

I notice the error happen on the `async for` line. But if i do try-catch around the for loop, then it would cause the entire loop to break when only one tool has an error. Maybe I'll need to use `anext()` with While loop instead of for loop.

Another problem is I'm not sure about the kind of message that I should send to OpenAI to tell it that we have a ValidationError going on. Is it simply a `role='assistant'` message?

**Comment by willbakst** [comment] 2024-08-13 23:10
1. We don't have a great way currently for catching a single issue when streaming; however, generally I think it's probably a good slow to catch the error, stop the stream, and try to stream again since you'll want to have a fully successful stream (e.g. what happens if you catch a single tool error but insert other successful tools in subsequent calls that then cause downstream issues because you actually needed the failed tool to be fully successful). Can you walk me through the use-case where you wouldn't want to restart / retry the whole stream? If this seems useful, I can look into adding a feature for catching such errors more easily.
2. For OpenAI I would generally include the error as an assistant message (since it was the assistant that made the error) followed by a user message mentioning there was an error and that you'd like the assistant to correct the error and try again. This flow should also work across all providers since there are some providers that require alternating assistant / user messages.

**Comment by off6atomic** [comment] 2024-08-14 05:53
I agree with this. I think invalid arguments error is a painful problem to have, especially when they can happen frequently. Ideally we should never have to deal with these errors at all. Structured outputs is probably the way to go.

For other errors that happen inside the tool execution itself, you can catch it and return error message as string inside the function so it's much easier to deal with than the invalid argument error. You also don't have to write an assistant message to indicate the error because the tool output already contains the error message.

**Comment by willbakst** [comment] 2024-08-14 06:20
Even if the tools themselves are stateless, the LLM may need all stateless tools to be called successfully to have a successful subsequent step, which is why I recommend restarting the entire stream.

However, if you're certain that this is not the case and you want to be able to have a mixture of successful/failed tool calls, I can see it being useful to have support for catching these errors at the point of tool construction so you can avoid stopping the stream.

My initial thought would be to provide some interface where you could supply an error handler that would catch and handle the tool construction without breaking the loop. Need to think about this more deeply.

**Comment by off6atomic** [comment] 2024-08-14 08:28
I think halting the entire loop instead of only one tool call is OK. What I probably need the most here is a way to prevent the error in the first place, like using the structured outputs approach from OpenAI.

If we can have example for structured outputs, that'd be best.

**Comment by willbakst** [comment] 2024-08-14 09:00
1. This has much better support in v1, including much improved documentation. Of course, we will be continuously iterating on this documentation to ensure anything that isn't clear becomes clear (and anything lacking is implemented).
2. 100% correctness is difficult. Things like reinsertion of validation errors can definitely help here, but ultimately I believe this will be the job of the model providers (such as the new OpenAI approach you've mentioned). Worthwhile I think post release to focus on better support for their new structured outputs as our existing support is still in beta.

**Comment by off6atomic** [comment] 2024-08-14 09:51
I agree the 100% correctness is difficult in general. I was thinking about OpenAI specifically.
It should be nice to start your LLM dev journey with OpenAI and never have to worry about wrong arguments.

**Comment by willbakst** [comment] 2024-08-18 21:27
Revisiting this:
1. I realized in your original post, you ask for the weather in California, and then it fails to validate "California" against your list of accepted literal string values (which explains the original validation error). This is expected behavior imo since it's correctly extracting "California" as the location but then failing at the validation stage
2. Interestingly, I just tried this with `gpt-4o` and `gpt-4o-mini` and it does what you originally expected and provides e.g. "Tokyo" even though you're asking for California. This seems like bad behavior from the model, but at least it aligns with your original expectations.

I'm going to close this issue, but feel free to reopen if you have any further concerns or questions.

**Closed by willbakst** 2024-08-18 21:27 UTC
Labels: Question

**Comment by off6atomic** [comment] 2024-08-19 05:08
The example I provided is not a good example. In some cases, the model fail to do both the extraction and the validation.

For example, you could ask the model to answer "Is 2+2=4?" and then you allow boolean answer, but the model answer int (e.g., 1) instead. This is definitely not expected answer. I've found it doing this sometimes in my own fashion-related prompt.

**Comment by willbakst** [comment] 2024-08-19 20:13
[This doc](https://mirascope.io/docs/latest/integrations/tenacity/) covers how to implement retries with validation errors across all the various call types in v1 :)

As for the OpenAI Structured Outputs, we have that in beta and are working on bringing that out of beta in the coming release. I've created a separate issue to track that work:
https://github.com/Mirascope/mirascope/issues/432
